import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Herobanner from "@/components/herobanner";
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Herobanner/>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
